### ISSUE TITLE
dislike (negative star) a repo

### ISSUE THREAD

**Issue by oprogramador** [isaacs/github#1455]
I would like to dislike a repo (in a similar way I can dislike a youtube video or a GitHub comment) when I notice:
- it has some major bugs
- there are some vulnerabilities
- it has some undocumented features
- many features are not covered by any tests
- the code is extremely ugly
- there are no answers on issues/ opened PRs
- the performance is extremely low

**Comment by ghuntley** [comment]
No

**Comment by oprogramador** [comment]
@ghuntley why?

Sometimes there can be a repo with many stars which just doesn't work or which is even a virus.

**Comment by oprogramador** [comment]
@azjezz @jackbuehner @wcoder @m1guelpf @SimpliCodin @rfschubert @MauricioFerraz @coliff

Could you explain why you are against?
IMO it's a very important feature (maybe even the most important missing feature on GitHub) because it would be clearly visible if a repo has some major bugs, vulnerabilities etc.

**Comment by jackbuehner** [comment]
@oprogramador 

A dislike button does not make that information easily visible. In my experience, dislikes tend to happen more when someone has been offended. Additionally, once someone has disliked a repository for one of your listed reasons, that person is unlikely to return to the repository and un-dislike it once the issue is fixed.

Rather than a dislike button, maybe there should the ability for users to leave reviews for repositories that have the issues you listed. The reviews could include rating sliders for certain aspects such as code quality or dev response to issues and PRs.

**Comment by oprogramador** [comment]
@jackbuehner 

Thanks for your feedback.
I created
- https://github.com/isaacs/github/issues/1562
- https://github.com/isaacs/github/issues/1561
- https://github.com/isaacs/github/issues/1560
- https://github.com/isaacs/github/issues/1563

**Comment by guochengli** [comment]
@jackbuehner "…that person is unlikely to return to the repository and un-dislike it once the issue is fixed." Nice point. But I think it is acceptable that there is a way to tell github users explicitly a repo is really bad or evil.
