### ISSUE TITLE
Parse markdown in milestone description

### ISSUE THREAD

**Issue by Logerfo** [isaacs/github#1579]
GitLab has this feature and it's pretty useful to better describe the milestone objectives.

**Comment by AJLeonardi** [comment]
I can't believe this doesn't exist.

**Comment by jonaslampe** [comment]
Would love this!

**Comment by jlsneto** [comment]
Please, I need it! 🙏

**Comment by Trillyy** [comment]
Looks like this does work, but only partially.
**abcd** is actually bold, but there's no way to go to the new line

**Comment by eupraxis1981** [comment]
Just realized it didn't to this as well -- all text boxes should support markdown -- just too useful.

**Comment by MarcvdSluys** [comment]
Our team would like to use the Milestone's description box to lay out the planning for each Milestone of a newly developed code (using (un)numbered lists), from which we can draft the Issues.  

Currently, this is impossible, since the structured document is displayed as a single paragraph... :-(  It would be awkward to go to a different cloud service to make and maintain the planning and then come back to GitHub to do the actual work.

**Comment by spyd3r** [comment]
Rendering markdown in milestone descriptions would be very useful. Comparing gitlab with github, one looks very good while the other...doesn't.

**Gitlab**
![gitlab-milestone-with-markdown](https://user-images.githubusercontent.com/1216237/79714841-3cc99700-828f-11ea-94f3-93ff9b52558c.png)

**Github**
![github-milestone-without-markdown](https://user-images.githubusercontent.com/1216237/79714866-4b17b300-828f-11ea-8a2e-e7b98c75aedc.png)

**Comment by wesselstudios** [comment]
I would love to have support for this as well! Just throwing my hat into the ring.

**Comment by Daniel-Kurth** [comment]
This feature would greatly improve my projectmanagement.

**Comment by moon-bits** [comment]
Come on...**one year has passed**. This seems to be such a basic feature to have.

No one understands the milestone description when everything is being put into one line.

**Comment by carlosparadis** [comment]
I landed on this page thinking I was doing something wrong when creating bullet lists. Guess not :-/

**Comment by v360-eduardo-marques** [comment]
same here. really thought I was doing something wrong :-(

**Comment by minmossi** [comment]
Still no progression?

**Comment by mitselek** [comment]
Who on Earth does own GitHub?

**Comment by tischoore** [comment]
Any progress?

**Comment by alanlawrence** [comment]
I also landed on this page trying to work out why my Milestone description markdown wasn't working. Please add markdown.

**Comment by jeffschwartz** [comment]
Yup!

**Comment by botatoes** [comment]
Hi all! I'm a PM at GitHub. Just wanted to let you all know this has been shipped yesterday. Please let me know if you have any feedback. I'll check back on here periodically. :) 

Just a quick note, because issues is a big part of milestones, milestones are truncated by default. Markdown will render when you expand the milestone.
