### ISSUE TITLE
Combine Issues and their PR's in the Project Board.

### ISSUE THREAD

**Issue by smeijer** [isaacs/github#1717]
I'm having both issues and pull-requests on the project board. It would be nice if the issue would "embed" the PR once there is 'fixing' one. Basically, just like a note already embeds issues, I would like an Issue to embed PR's. And PR's to embed Issues.

So, if we have a `pull-request #2` that includes `fixes #1` in the body, the cards on the project board, should be linked.

If someone adds the issues to the board, `issue #1` should include `pull-request #2`. If someone adds pull-requests to the board, `pull-request #2` should include `issue #1`.

Again, just like notes already do.

**Comment by labrose** [comment]
👋 Hello! I'm a Product Manager at GitHub focused on issues and projects. We just rolled out an [update to the project board issue card](https://github.blog/changelog/2020-02-04-project-issue-cards-include-linked-pull-requests/) so that it now includes the closing pull requests that are associated. Here's an example:

<img src="https://user-images.githubusercontent.com/22751162/73779151-25bfe200-4741-11ea-9341-1a8c1a7f0edc.png" width=350px />

If you try this out, let me know what you think and if there are other ways we could improve in this area!

**Comment by smeijer** [comment]
:scream: I've noticed the update before I even noticed your comment. It's awesome! Exactly what I was looking for.

Thanks @labrose!
