### ISSUE TITLE
XML tags and text between then is not visible

### ISSUE THREAD

**Issue by MarcoCostantini** [isaacs/github#1801]
When I report a bug, and in the text I use XML tags (because I want to write about XML stuff), then the XML tags and the text between them is not visible.
For instance, if i write
< OMS cd="nums1" name="pi"/>
without the space between < and O, it will be not visible: check the line below:
<OMS cd="nums1" name="pi"/>

**Comment by jimmywarting** [comment]
github issues support a few simple html tags along with markdown syntax - thats why it could sometime be useful to post xml/html tags in github issues. (I often see the detail tag being used in github issues - mostly by bots) it's a neat feature

that also the reason why you can't post the xml tag you like

also it makes a horrible tab indentation if you could just write just plain xml in the issue it would just look like this:

---

&lt;!DOCTYPE html&gt;
&lt;html lang=&quot;en&quot; dir=&quot;ltr&quot;&gt;
  &lt;head&gt;
    &lt;meta charset=&quot;utf-8&quot;&gt;
    &lt;title&gt;&lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;
    
  &lt;/body&gt;
&lt;/html&gt;

---

What you actually want is to put it inside a code block so that the indentation works just like a charm

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>
```

you can even add syntax color to the markup

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    
  </body>
</html>
```

but when you just need a short one liner then wrap it in backtickets `

Here are a few example of how you can post your data

![Skärmavbild 2020-05-12 kl  17 31 51](https://user-images.githubusercontent.com/1148376/81713776-967c4600-9476-11ea-8186-6544b47def35.png)

**Comment by jimmywarting** [comment]
This should be closed IMO
