### ISSUE TITLE
Do GitHub employees respond here?

### ISSUE THREAD

**Issue by trusktr** [isaacs/github#1817]
I'm curious.

I opened an issue about making an official repo at https://github.com/github/explore/issues/1536.

**Comment by erkinalp** [comment]
@isaacs is a GitHub staff.

**Comment by cirosantilli** [comment]
isaacs does not reply here in a long time.

Sometimes others come, but its not super common.

**Comment by bl00mber** [comment]
@erkinalp he is responsible for npm, I guess. He wasn't a member of github when this repo was created.

**Comment by TPS** [comment]
Recently, only since [the Project Paper Cuts initiative](https://github.blog/2018-08-28-announcing-paper-cuts/), we've had actual GitHub employees respond on issues they're working on implementing.  Additionally, beside Isaacs, there's @ least 1 other GitHub employee who's a collaborator here.  Also, #6 is the canonical request for an official support repo.

**Comment by TPS** [comment]
#1985 is the ultimate response.
