### ISSUE TITLE
Emojis are overlapping with text

### ISSUE THREAD

**Issue by szepeviktor** [isaacs/github#1820]
Hello!
Couple of days ago emojis on GitHub overlap with the following text

![kép](https://user-images.githubusercontent.com/952007/84627312-0010c980-aee7-11ea-937c-031e2be344c3.png)

Could it be a recent Windows 10 update? Or Firefox? Or GitHub??

|||| 🦊 ||||

**Comment by julien-langlois** [comment]
The problem also appears on the text to the right of the badges located under the GitHub profiles.

**Comment by duianto** [comment]
Confirmed. Here's an example: ![chrome_2020-06-15_20-22-03](https://user-images.githubusercontent.com/13420573/84692323-f5395180-af45-11ea-90d7-ed727aa17a03.png)
source: [lsp][dart] Fix dart layer https://github.com/syl20bnr/spacemacs/pull/13518

Windows 1903
Google Chrome | 83.0.4103.97 (Official Build) (64-bit) (cohort: Stable)

**Comment by duianto** [comment]
I suspect that they (GitHub) already was working on a solution, because it seems to have been fixed.

The spacing is now the same in both:
- Google Chrome: 
![chrome_2020-06-16_07-23-13](https://user-images.githubusercontent.com/13420573/84734879-673f8400-afa2-11ea-86c5-71ac2f1a8fb2.png)

- Mozilla Firefox: 
![firefox_2020-06-16_07-23-26](https://user-images.githubusercontent.com/13420573/84734938-89390680-afa2-11ea-8916-9ad13e9d532e.png)

The Firefox screenshot is more dim because I'm not logged in in Firefox, therefore it's disabled.

**Comment by szepeviktor** [comment]
Yes.

![kép](https://user-images.githubusercontent.com/952007/84735767-90f9aa80-afa4-11ea-85c3-dac64e86c283.png)
