### ISSUE TITLE
"Reply by email" leading to beginners "doxxing" themselves

### ISSUE THREAD

**Issue by Gadgetoid** [isaacs/github#1934]
The "Reply by email" feature- whereupon the contents of an email are posted publicly when an email notification is replied to- has a serious flaw that can lead to unintended and unwanted data disclosure.

Should a user have an email sign-off containing their full name, telephone number, or any other personal information (which we can safely assume they wish to share with the imagined expected recipient of the email, not the entire internet) then "Reply by email" will lead to that information being interpreted as and posted as part of the Issue response.

Since editing an issue preserves its history, the only recourse is to delete the response outright and contact the user to set them straight. This relies on prompt and correct action from a repository owner, which is not always feasible.

I have a strong preference toward being able to turn this feature off across the projects I maintain, since it is a potential avenue for targeted harassment.

**Comment by markcellus** [comment]
It would be no different from responding to an email with Reply-All. Is the person not aware that they are responding to a GitHub issue? I wouldn't want another GitHub user  having control over what Github features I can use.

**Comment by jonorthwash** [comment]
> It would be no different from responding to an email with Reply-All.

It's different in that instead of going to only the people involved in the issue, it gets posted publicly.

> Is the person not aware that they are responding to a GitHub issue?

As @Gadgetoid said, this is a problem for beginners, who don't have experience with GitHub.  They may or may not know that the message contents will be posted to the issue, but more crucially they are at the very least not connecting the dots between "reply is interface for posting to issue", "reply contains personal information", and "reply contents will be viewed publicly".  And yes, they may just interpret is as "oh the devs emailed me".  Even those of us who are experienced with this have had to learn to structure such replies differently than if we had received an email with the same contents (no signature, maybe no greeting, etc.).

> I wouldn't want another GitHub user having control over what Github features I can use.

I can think of other approaches to solve this ("WARNING"s in the email should be a baseline, could have filtering for such things like sourceforge mailing list archives, etc.), but it is a real concern.

**Comment by markcellus** [comment]
> this is a problem for beginners, who don't have experience with GitHub

So we should disable a fundamental way users communicate through GitHub that's already been available to them for years just because beginners don't know how to use Github? There's a lot of documentation on how Github works.

**Comment by Gadgetoid** [comment]
> > this is a problem for beginners, who don't have experience with GitHub
> 
> So we should allow repo owners to disable a fundamental way users communicate through GitHub that's already been available to them for years just because beginners don't know how to use it properly?

Yes.

**Comment by markcellus** [comment]
If one buys a new oven, uses a feature, and the oven blows up and burns them, asking the manufacturer to disable the feature for all future purchasers because one didn't read the manual about the feature before they used it doesn't make much sense.

So what happens when a user who's been relying on this feature tries to use it when it's disabled? The email just bounces back? And it keeps randomly happening across certain repos? Disabling the feature seems like a rather short-sighted solution to a problem that already has one. 

I really hope Github never allows this feature to be disabled.

**Comment by Gadgetoid** [comment]
You’re welcome, if not *encouraged*, to never interact with any of the GitHub repositories I manage so that this terrible inconvenience doesn’t trouble you.

**Comment by TPS** [comment]
This looks to have been quietly mostly solved.  I just received a notification for a reply that was done by e-mail, & all the "doxxing" stuff had been stripped out, leaving only the reply (& e-mail client ad, which is how I knew).  Anyone else confirm?

**Comment by Gadgetoid** [comment]
I’ve had to delete telephone numbers from reply-by-email replies as of a week or two ago so we’ll see!
