### ISSUE TITLE
📣 [NOTICE] This repo is being deprecated

### ISSUE THREAD

**Issue by michellemerrill** [isaacs/github#2035]
As we’ve been [discussing](https://github.com/isaacs/github/issues/1985) the last several months, [we are working on deprecating this repo](https://github.com/isaacs/github#important-note-github-now-has-an-official-feedback-repository-open-a-discussion-there-to-ask-questions-or-discuss-bugs-this-repo-is-deprecated) in favor of moving to our discussions platform. Starting today, we have disabled the ability to create issues on this repo.  _Note: you can still add comments to issues previously opened._

We invite you to head over to [Feedback Discussions](https://github.com/github/feedback/discussions) and share your product feedback and questions directly with us!  Prior to making a new discussion, please take a look at previous discussions to see if someone else has already brought forward a similar idea or suggestion. If you find a similar discussion, reply with additional details or **upvote** the discussion to signal your support rather than creating a new discussion.

**Comment by aspiers** [comment]
@michellemerrill Thanks a lot for the update.  It does make me a little nervous that this has been deprecated before a migration strategy has been announced (or if it has, please forgive me for missing it and let me know where I should have seen it).

Currently I see a risk that a scenario such as the following *could* play out (please forgive the wild, totally unfair, and hopefully inaccurate speculation / crystal-ball gazing, done purely to demonstrate the risk, and not to insinuate anything):

- The decision to perform a migration gets eventually reversed because it is decided to be too complex and not worth the effort (IMHO this would be a significant error of judgement, so hopefully that's not going to happen).
- Instead GitHub decides that it is enough to keep the status quo of isaacs/github for a grace period (i.e. closed for new issues, allowing new comments on existing issues), and at the end of which to totally lock it so that it's permanently frozen.
- Meanwhile, no mechanisms are provided for the community to contribute to curation of the official Feedback Discussions, instead leaving it in the hands of a small team of GitHub employees.
- Over time, GitHub decides to lower the priority of this curation, and correspondingly reduces resources.
- (Even if this didn't happen, and even if that team were to do an excellent job for the next 100 years, it could never achieve the totality of what could be achieved if the community is also given the freedom to contribute to curation.  For example, imagine what a mess StackOverflow would be if the whole thing was managed by a single team at a single company, without contributors being able to earn the right to help with curation, moderation etc.)
- The community then finds itself in a similar situation it did in circa 2013, where it needs a place to track issues in a highly structured and relatively permissionless way, but GitHub is not providing that place.
- To give a concrete example, imagine if labels were not being carefully applied and maintained for all the topics in the official forums
- The community creates another issue tracker to work around the problems, thereby fragmenting the community yet again, causing the same issues to be discussed redundantly not only here in isaacs, in dear-github, and in the official Discussions forums, but also in other new unofficial places.

Now, this is probably the worst possible scenario, but what worries me is that it's also the "path of least resistance", and therefore in the absence of significant impetus to create a different trajectory, it would seem the most likely outcome.  That's why I have previously [warned about this](https://github.com/isaacs/github/issues/1985#issuecomment-906813728) on [a few occasions](https://github.com/isaacs/github/issues/6#issuecomment-858989005).

So it would be fantastic to hear some reassurances that a) a migration *is* happening in [a manner which addresses the concerns raised by the isaacs community](https://github.com/isaacs/github/issues/1985), and that b) a significant level of community curation will be preserved post-migration.

Thanks again for listening, really appreciate it!

**Comment by michellemerrill** [comment]
This repository has now been [archived](https://github.com/isaacs/github/issues/2035). We continue to build out our public feedback discussions space over at `github/feedback` and evolve its use and functionality as a way for discussing how the product could improve as a community. We invite you to join us there!  

We [disabled the ability to create new issues](https://github.com/isaacs/github/issues/2035) on this repository over a month ago, with the intent to migrate existing issues over to GitHub Discussions. After considering this more, we decided that migrating issues could cause problems with authorship and original intent. To maintain that authorship, we invite you to migrate your feedback to [github/feedback/discussions](https://github.com/github/feedback/discussions). 

More and more GitHub Product team members continue to join the conversations there and track these improvements with the community in a centralized way. If you have a favorite feature or suggestion here, we’d love it if you could post it in that new space (copy-pasting is fine) with a link to the original `isaacs/github` issue so we don’t lose the history. For older issues, it might also be a good time to update your feedback with any new insights, given that the product has gone through quite a lot of change these last couple years. This will help us keep improving GitHub in ways that deliver what you all want and need.

Thank you to everyone that has participated here as your insights have been invaluable to our team. This repo is going to live on in an archived state, and we’ll continue to draw from the wealth of input you’ve all provided. We hope you’ll continue to collaborate with us in our [discussions](https://github.com/github/feedback/discussions) space -- be on the lookout for new categories, usability and feedback interactions!

**Comment by isaacs** [comment]
End of an era, love to see it.  Thanks, GitHub <3
