### ISSUE TITLE
Subscribe to issues individually on a watched repo

### ISSUE THREAD

**Issue by jmm** [isaacs/github#356]
I want to be able to subscribe to issues individually on a repo I watch just like I can on a repo I don't watch. Currently when I watch a repo, on each issue I get an `Unsubscribe` button with this caption:

> You're receiving notifications because you're subscribed to this repository.

I may decide to unwatch the repo at some point, but still want to get notifications for updates to those specific issues.

**Comment by jmm** [comment]
Ivan Žužak from GitHub replied that you can click `Unsubscribe`, then click `Subscribe` to subscribe to the thread directly. I assume this means that if you unsubscribed from an issue while watching the repo, you'd have to unwatch then re-watch the repo to get back to getting notifications on those issues.

**Comment by piotr-dobrogost** [comment]
Why is this closed while the issue is still present?
Having workaround is one thing and fixing the issue is another.
The fix seems simple; leave the current info under "subscribe" button as is (i.e. show it when someone is watching repo) but make button "subscribe/unsubscribe" based on weather one is watching or nor specific issue.
