### ISSUE TITLE
Detecting "merged" Pull Requests that were not accepted with git-merge

### ISSUE THREAD

**Issue by Wopple** [isaacs/github#363]
We "merge" our PRs via rebase / cherry-pick and amending commit messages with "closes #". However, this gives the PR the "closed" status as if you closed the pull request without accepting the changes. This causes our JIRA integration to think the pull request has been declined.

It would be nice if we could have a "rebased" status or perhaps another workaround so our JIRA integration can detect accepted pull requests that were not merged. Having the option to mark the PR as such through a commit message or through the website would be nice as well.

**Comment by pdilyard** [comment]
+1

**Comment by miketwo** [comment]
+1. Though I think a workaround is to re-push the altered commit to the PR branch first (using force if necessary), then merge into master.

**Comment by cvrebert** [comment]
Very similar to #2.

**Comment by c0b** [comment]
:+1: for this; a lot of projects like nodejs development still favors the original linux kernel development style: some core maintainer add `Reviewed-by: ` `Acked-by:` and series of those and commit and push for you, since the commit msg has somewhat changed, it's not the original commit github can't detect as merged; but the content of changes are the same

in this comment, @jasnell has to manually say `Landed in 983a809` and close the PR which is inconvenient; as I think @github should detect this case and mark nodejs/node#6350 as merged automatically.

1. https://github.com/nodejs/node/pull/6350#issuecomment-213651363
2. https://github.com/nodejs/node/commit/983a809

**Comment by Wopple** [comment]
With the ability to rebase or squash in the UI, this is mostly a non-issue now.
