### ISSUE TITLE
Different defaults for indent settings on github.com and gist.github.com.

### ISSUE THREAD

**Issue by chadwhitacre** [isaacs/github#57]
First reported by @shurcooL in https://github.com/whit537/github.com:

> ![](http://shurcool.github.io/bettertogether/img/default_indent_settings_github.png)
> 
> ![](http://shurcool.github.io/bettertogether/img/default_indent_settings_gist.png)
> 
> Fix: Make consistent default values for indent mode and indent size.
> 
> Pro-level: If your defaults aren't my preferred values, please let me [override](https://github.com/shurcooL/preferences.content/blob/master/README.toml) the defaults in my GitHub settings. Personally, I like tabs of size 4.

**Comment by darkuranium** [comment]
Just ran into this while trying to figure out if there was a way to set the default. I find most people (including me) like tab size of 4, so I find the default to be 2 weird anyways.

But of course, the best solution would be to have it user-settable.

**Comment by Ledzz** [comment]
+1 for user settable

**Comment by shurcooL** [comment]
Whoops, I didn't see this when I later re-reported it as #615 with working images. @whit537, mind closing this one since it's a duplicate?

Some people are saying +1 to user customizable indents, but the original bug report was about inconsistent defaults, and that has been fixed. I suggest opening a new feature request issues instead.

**Comment by TPS** [comment]
Fixed per https://github.com/isaacs/github/issues/615#issuecomment-198805971
