### ISSUE TITLE
Be able to force organization members to use 2FA

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [isaacs/github#570]
Today is not possible to force all members of the organization to use two factor authentication. This will remove organization management stress and potential security risks.

**Comment by hwine** [comment]
Agreed - especially after Github's [recent announcement on password attacks](https://github.com/blog/2190-github-security-update-reused-password-attack).

Since it is not possible (for good reasons) to determine the 2FA status of an account prior to inviting them to your organization, we're always behind the game. (If anyone is interested, I run an ugly [daily job](https://github.com/mozilla/github-org-scripts/blob/master/enforce_2fa.py) to notify & remove such new members.)

**Comment by hwine** [comment]
Per [README](https://github.com/isaacs/github/blame/master/README.md#L23), here's the latest github response:
> Hi Hal,

> Thanks for getting in touch, and thanks for sharing your thoughts with us about enforcing 2FA for organization members. You're definitely not the first person to suggest this feature, and I will be sure to share your comments with the relevant engineering teams here.
> 
> Please let us know if you have any other questions or if we can help with anything else!
> 
> Best regards,
> Ben

**Comment by TPS** [comment]
Solved on Sep 14, 2016 via https://help.github.com/articles/requiring-two-factor-authentication-in-your-organization/!  

@VelizarVESSELINOV @cirosantilli Please close FTW. ☺

**Comment by BevanR** [comment]
It would be nice to be able to require this per team instead of (or as well as) per organisation.
