### ISSUE TITLE
Blog accuracy

### ISSUE THREAD

**Issue by Pablo-Ivan** [isaacs/github#616]
I was reading GitHub's Blog and there was an article explaining that an user project is hosted at https://your-project.github.io. But as far as I know (I have dozens of GitHub projects online), this isn't correct, since it is: https://<username>.github.io/project-name.
![GitHub Blog] (https://cloud.githubusercontent.com/assets/10409758/13902834/3104b0c2-ee22-11e5-9b21-d3ecaacdc463.png)

**Comment by captn3m0** [comment]
A link to the blog post in question might be helpful here :+1:

**Comment by Pablo-Ivan** [comment]
https://github.com/blog/2128-creating-a-new-contributor-on-ramp

**Comment by cirosantilli** [comment]
He's talking about GitHub Pages: as linked on the same paragraph yo u quote: https://pages.github.com/

Please read more on it and it will become clear: you need a magic `gh-pages` branch for it to work, and possibly an even more magic `<username>` named repository to use the root.

Since it's linked on the same paragraph, I think it is fine.
