### ISSUE TITLE
Linking to file with current commit hash

### ISSUE THREAD

**Issue by andrewthad** [isaacs/github#625]
Often, I will be answering a question on Stack Overflow, and I want to link to a line of code in a public repository. So, I go to the repository, often using the master branch, and navigate to the file I want. But, I can't just link to the file I've navigated to. If I do that, then after new changes get pushed to the master branch, the line number will point to the wrong place. Or even worse, the file might be removed in a future version.

So, instead I need to view that file on a particular commit. This ensures that the link I provide to the code stays good forever. At the moment, there's no easy way to get this link once I'm already on the page on a branch. The most recent commit hash is listing near the top right, but it links to the commit itself, not the file on that commit. I would like a link to that to be provided as well, much like a "permalink" is provided by most blogging platforms.

**Comment by TPS** [comment]
I think this is already provided, e.g. to link to https://github.com/andrewthad/yesod-table/src/Yesod/Table.hs line 72 @ https://github.com/andrewthad/yesod-table/commit/848e2fbf6a5edfef41a025735f9f65cd69b89724:

https://github.com/andrewthad/yesod-table/blob/848e2fbf6a5edfef41a025735f9f65cd69b89724/src/Yesod/Table.hs#L72

I find this by going to commit history @ point I choose, hit <kbd> __`<>`__ </kbd> to right of commit hash, browse to intended file, & then choosing line like normal.  As usual, linkable address will be in addressbar above.

**Comment by andrewthad** [comment]
@TPS That's the way that I currently do it, and it does work, but I usually when I browsing a repo to find something I want to link to, I don't remember to go to the latest commit first. So, I end up on:

https://github.com/andrewthad/yesod-table/blob/master/src/Yesod/Table.hs

But then getting to

https://github.com/andrewthad/yesod-table/blob/cebc98ab2ee0b2b40d44e51bb82a0ca8649df888/src/Yesod/Table.hs

from this point is harder than I would like.

Actually, nevermind. I just realized that you can get to the history of a particular file once your already on the file. It's two clicks away instead of one, but that's still close enough. Thanks!

**Comment by ComFreek** [comment]
> I just realized that you can get to the history of a particular file once your already on the file. It's two clicks away instead of one, but that's still close enough


Maybe GitHub changed the UI or I am unable to find that way of two clicks because I always need three clicks:

![3 clicks necessary to go from a file on master branch to that file in the latest commit history](https://user-images.githubusercontent.com/1827709/42123112-98957fae-7c4c-11e8-9469-05617352df9f.gif)

For me three clicks *per file* I am linking to are a little bit too much.

Worth remarking is that the menu displays when having highlighted lines in a code file offers a "copy permalink" option which indeed copies the permalink to the file in its latest commit version to clipboard:
![Menu after having highlighted lines in a code file offering a "copy permalink" option](https://user-images.githubusercontent.com/1827709/42123158-4dd14a9c-7c4d-11e8-9a96-24c1c73c54e0.png)

This is fine! However, I feel it is a bit asymmetric: I can't do this for non-code files (e.g. Markdown or image files) and this forces me to highlight some lines.
