### ISSUE TITLE
Native ability to close an issue as a duplicate of another issue

### ISSUE THREAD

**Issue by KeyboardPerson** [isaacs/github#897]
Something a bit similar to how StackOverflow closes questions as duplicates of other questions.

**Comment by gpadak** [comment]
Today GitHub shipped a feature that helps new issue creators see duplicate or otherwise potentially related issues that already exist in the repository. https://blog.github.com/changelog/2018-11-05-related-issues/

[Here's how it looks in practice!](https://twitter.com/natfriedman/status/1059865385242058752)

<img width="790" alt="new_issue_ _isaacs_github" src="https://user-images.githubusercontent.com/1852630/48092291-43b73380-e1da-11e8-82e4-c07dd181f48d.png">

**Comment by clarkbw** [comment]
Closing
