### ISSUE TITLE
Pull Request - Multiple Reviewers

### ISSUE THREAD

**Issue by bkuberek** [isaacs/github#92]
Hi,

This is a feature request to add multiple reviewers to a pull request. At the time, each pull request can be assigned to a member who will review and merge the change set. However, we are used to having multiple developers reviewing the code and either +1 or -1 it. Although it can now be accomplished in the comments, it is not easily seen who has approved the pull request.

So I think we could add a "Reviewers" field next to the "Assigned" field. This will be an official list of those invited into the discussion and who feedback is taking into consideration before the "assignee" merges the change set. On the right column we could have a list of reviewers and whether they approve or disapprove.

Also, when a pull request is merged, the merge commit would have a commit message such as the following:

```
Reviewed-on: https://github.com/org/project/pull/7
Reviewed-by: Jane Doe <jane@example.com>
Reviewed-by: Jon Doe <jon@example.com>
Signed-off-by: Dan Spear <dan@example.com>
```

**Comment by xcarol** [comment]
+1

**Comment by aschokking** [comment]
+1

**Comment by neoshadybeat** [comment]
:+1:

**Comment by derrickj3000** [comment]
:+1:

**Comment by ryazmin** [comment]
+1

**Comment by samstr** [comment]
:+1:

**Comment by kurman** [comment]
+1

**Comment by sathichowdhury** [comment]
+1

**Comment by einarth** [comment]
+1

**Comment by d2l-mderidder** [comment]
+1

**Comment by TurkeyFried** [comment]
:+1:

**Comment by avaliani** [comment]
+1

**Comment by DavidBruant** [comment]
+1

**Comment by kstefanini** [comment]
+1

**Comment by AntoineTurmel** [comment]
+1

**Comment by t8g** [comment]
+1

**Comment by mymyoux** [comment]
+1

**Comment by zaiboot** [comment]
+1

**Comment by jxstanford** [comment]
+1

**Comment by lexjacobs** [comment]
+1

**Comment by stugots** [comment]
+1

**Comment by saury07** [comment]
+1

**Comment by eitanshp** [comment]
+1

**Comment by KaizenCode** [comment]
+1

**Comment by lukehutton** [comment]
+1

**Comment by 0xporky** [comment]
:+1:

**Comment by EricHype** [comment]
+1

**Comment by carlossless** [comment]
+1

**Comment by mace707** [comment]
+1

**Comment by minhnhat2807** [comment]
+1

**Comment by senkal** [comment]
:+1:

**Comment by nicolls1** [comment]
+1

**Comment by D-system** [comment]
+1

**Comment by tallytalwar** [comment]
:+1:

**Comment by playground** [comment]
:+1:

**Comment by playground** [comment]
Is this feature going to be available anytime soon?

**Comment by dhruvparmar372** [comment]
+1

**Comment by azizhk** [comment]
+1 :+1:

**Comment by dxtr026** [comment]
+1

**Comment by riansanderson** [comment]
+1

**Comment by tejasv02** [comment]
+1

**Comment by snicko** [comment]
+1

**Comment by dyk0** [comment]
+1

**Comment by MaximProshin** [comment]
+1

**Comment by jrencz** [comment]
:+1:

**Comment by Pushplaybang** [comment]
+9000

**Comment by siddhuwarrier** [comment]
+42,895

**Comment by Pushplaybang** [comment]
This is probably the only thing my team misses from bitbucket is the ability to see a clear approved number once all issues have been dealt with.

**Comment by lh-cduane** [comment]
++

**Comment by Mark-Swinkels** [comment]
+1 Really miss this from other tools, assigning reviewers and having them be able to mark their review as done is a key part of our workflow. Today we are left with @ mentions and comments for done.

**Comment by aaudiber** [comment]
+1

**Comment by jez9999** [comment]
I gotta ask, if all you guys are "just missing this thing from Bitbucket", why aren't you just using Bitbucket?  Why reward Github for having fewer features?

**Comment by snicko** [comment]
Because there's other functionality that GitHub has that Bitbucket doesn't, plus inertia.

**Comment by jez9999** [comment]
What other functionality?  The network graph?  You can get something like that with any GUI that shows a git repo's history.  Meanwhile, Bitbucket has better JIRA integration (obviously) and a more sensible pricing model than Github.

**Comment by paulmelnikow** [comment]
Yes, please.

**Comment by D-system** [comment]
Other missing feature in Bitbucket: show the date of the last change on a folder for any file inside it.

**Comment by adericbourg** [comment]
:+1:

**Comment by Sab8** [comment]
+1

**Comment by williammills** [comment]
+1

**Comment by ecoad** [comment]
+1

**Comment by sidonaldson** [comment]
+1

**Comment by CsabaSzabo** [comment]
+1

**Comment by ostlerc** [comment]
+1

**Comment by disciple97** [comment]
:+1:

**Comment by lakshbhasin** [comment]
+1

**Comment by Delkaspo** [comment]
+1

**Comment by mobilutz** [comment]
+1

**Comment by mrt123** [comment]
+1

**Comment by zerkowsm** [comment]
+1

**Comment by blueandgold** [comment]
:+1:

**Comment by asborisov** [comment]
:+1:

**Comment by NekoNova** [comment]
Any plans on getting this forward? We use the same workflow as bitbucket and really like to have multiple assignees

**Comment by stephen-cernota** [comment]
:+1:

**Comment by spacetag** [comment]
+1

**Comment by ushuz** [comment]
+1

**Comment by pchoi** [comment]
+1

**Comment by chadjaros** [comment]
+1

**Comment by danderson00** [comment]
+1 wow, lots of requests for this. This is a fairly critical feature that we are probably all working around using comments.

This is clearly a high value feature, please prioritise accordingly!

**Comment by mamaso** [comment]
+1

**Comment by mathieurivest** [comment]
+1

**Comment by jwallra** [comment]
+1

**Comment by tzmanics** [comment]
+1

**Comment by Berastau** [comment]
+1

**Comment by fuag15** [comment]
+1

**Comment by adamlacoste** [comment]
+1

**Comment by Hamled** [comment]
+1

**Comment by anassarr** [comment]
+1

**Comment by focs** [comment]
+1

**Comment by verrdon** [comment]
+1

**Comment by kirillshingel** [comment]
+1

**Comment by csiandreybeletsky** [comment]
+1

**Comment by razorvind** [comment]
+1

**Comment by ivandyatko** [comment]
+1

**Comment by zainadil** [comment]
+1

**Comment by mattohope** [comment]
+1

**Comment by rickcab** [comment]
+1

**Comment by yspotts** [comment]
+1

**Comment by hmanet** [comment]
+1 Please implement thius feature

**Comment by prasadkarkera** [comment]
+1

**Comment by emberTrev** [comment]
:+1:

**Comment by HonzaMikula** [comment]
+1

**Comment by twellspring** [comment]
+3

**Comment by marcomorain** [comment]
+1 :+1:

**Comment by mhueter** [comment]
+1

**Comment by alfre2v** [comment]
+1

**Comment by ForestJay** [comment]
:+1:

**Comment by markusbergh** [comment]
:+1:

**Comment by JKetelaar** [comment]
+1

**Comment by sam1111** [comment]
+1

**Comment by tpaliatayeva** [comment]
+1

**Comment by culli** [comment]
+1

**Comment by cluttered-code** [comment]
+1

**Comment by WanjaStier** [comment]
+1

**Comment by kenny-traderev** [comment]
+1

**Comment by leftofnull** [comment]
👍

**Comment by dbezzubenkov** [comment]
+

**Comment by dgvozd** [comment]
+

**Comment by minterior** [comment]
+1

**Comment by DanielYWoo** [comment]
+1

**Comment by markpfletcher** [comment]
+1

**Comment by Saimount** [comment]
+1

**Comment by zerkowsm** [comment]
https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests?utm_source=twitter&utm_medium=social&utm_campaign=multiple-assignees ?!?!

**Comment by Saimount** [comment]
Done ! :)

**Comment by ivandyatko** [comment]
Yey!

**Comment by gitbaron** [comment]
:+1:

**Comment by aspiers** [comment]
Firstly, **PLEASE STOP POSTING INANE +1 comments!**  [GitHub added a perfectly good mechanism for expressing your support and other reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) without spamming issues with useless noise, so please use it. `</rant>`

Now on to the actual topic ...

There have been significant new developments with GitHub since this issue was submitted in 2013:

- As mentioned by @zerkowsm above, [it is now possible to have multiple assignees on issue and PRs](https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests).
- GitHub now provides [a built-in PR review system with approval tracking](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features)

The stated context of this issue is "each pull request can be assigned to a member who will review and merge the change set", but based on the two developments above, this is no longer accurate, because:

1. multiple people can be assigned to the PR
2. as a result, it's no longer clear who has been assigned the separate responsibilities of reviewing and merging the PR.

For example, if two people are assigned, does that mean one is responsible for reviewing and the other for merging?  Or both for reviewing and one for merging?  Or both for reviewing, and both collectively for merging (even though ultimately only one can merge)?  With more than two assignees, this becomes even less clear.

Therefore whilst the *intention* behind this issue is still very much valid (IMHO), I think the issue itself needs slightly rephrasing, and rather than rewriting history by editing the original issue description, it would be less confusing and more transparent to close this issue and submit new ones which focus on the core problems which still exist with GitHub as it exists now:

1. The "Assignees" feature does not allow a distinction between "please review this PR" and "please ensure that this PR is driven to a resolution of being either merged or closed".
2. The new PR review system should support a configurable review policy, such as "all reviews require at least two approvals" or "all reviews require at least one approval from one of the maintainers".

I will file new issues for these now.

**Comment by aspiers** [comment]
@bkuberek Based on my last comment are you OK with closing this?

**Comment by aspiers** [comment]
@bkuberek Since #778 is now resolved, I think this issue should definitely be closed too.

**Comment by TPS** [comment]
@cirosantilli Based on the last few comments, close this resolved?

**Comment by jasonwbarnett** [comment]
+1

**Comment by ern** [comment]
+1

**Comment by CafeLungo** [comment]
+1. should be able to force multiple reviews.

**Comment by aspiers** [comment]
Jeez, some people are incapable of reading...

**Comment by aspiers** [comment]
Jeez, some people are incapable of reading...
