### ISSUE TITLE
Allow organization-level project boards to be publicly viewable

### ISSUE THREAD

**Issue by SamCarlberg** [isaacs/github#935]
Currently, organization-level projects can only be viewed by members of that organization. There should be an option for making a project viewable by anyone.

Relevant help article: https://help.github.com/articles/about-project-boards/

**Comment by SamCarlberg** [comment]
Reply from GitHub support:

> Hey Sam,
>
>Thanks for reaching out! I agree, it would be great to make organization projects publicly visible. I'll pass this on to our team as something to consider adding.
>
>Let me know if you have any other suggestions, or any questions!
>
>Cheers,
>Antonio
>GitHub Support

**Comment by sypets** [comment]
@SamCarlberg Are you sure this issue is still open? Because I looked at projects of an organization as a non-member and I can view the boards. Each project can be made private or public in the settings. 

![projects](https://user-images.githubusercontent.com/13206455/54471837-10a43280-47c0-11e9-868a-ad2ce7e2a859.png)

**Comment by clarkbw** [comment]
Yep, this has been fixed https://help.github.com/en/articles/changing-project-board-visibility
